# Generated by Django 5.0.7 on 2024-08-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientsignupdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=100)),
                ('clientemail', models.CharField(max_length=100)),
                ('clientpassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='contactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactname', models.CharField(max_length=100)),
                ('contactemail', models.CharField(max_length=100)),
                ('contactsubject', models.CharField(max_length=100)),
                ('contactmessage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='investorsignupdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investorname', models.CharField(max_length=100)),
                ('investoremail', models.CharField(max_length=100)),
                ('investorpassword', models.CharField(max_length=100)),
            ],
        ),
    ]
