# Generated by Django 5.0.7 on 2024-08-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduInvApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='investorapplicationdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investorfirstname', models.CharField(max_length=100)),
                ('investorlastname', models.CharField(max_length=100)),
                ('investoremail', models.CharField(max_length=100)),
                ('nomineefirstname', models.CharField(max_length=100)),
                ('nomineelastname', models.CharField(max_length=100)),
                ('investoraddress', models.CharField(max_length=100)),
                ('investorphonenumber', models.BigIntegerField()),
                ('nominemphonenumber', models.BigIntegerField()),
                ('investorphoto', models.ImageField(upload_to='photos/')),
                ('investorpancard', models.ImageField(upload_to='photos/')),
                ('investoradhaar', models.ImageField(upload_to='photos/')),
                ('investorbankstatus', models.ImageField(upload_to='photos/')),
                ('investorbankpass', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
