# Generated by Django 5.0.7 on 2024-08-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduInvApp', '0002_investorapplicationdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='loanapplicationdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applicant_loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Applicant_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('Applicant_first_name', models.CharField(max_length=50)),
                ('Applicant_last_name', models.CharField(max_length=50)),
                ('Applicant_dob', models.DateField()),
                ('Applicant_email', models.EmailField(max_length=254)),
                ('Applicant_phone_number', models.CharField(max_length=15)),
                ('Applicant_father_name', models.CharField(max_length=50)),
                ('Applicant_mother_name', models.CharField(max_length=50)),
                ('Applicant_father_phone', models.CharField(max_length=15)),
                ('Applicant_mother_phone', models.CharField(max_length=15)),
                ('Applicant_father_job', models.CharField(max_length=50)),
                ('Applicant_mother_job', models.CharField(max_length=50)),
                ('Applicant_marital_status', models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried'), ('nil', 'NIL')], max_length=10)),
                ('Applicant_house_number', models.CharField(max_length=10)),
                ('Applicant_street_name', models.CharField(max_length=100)),
                ('Applicant_post_office', models.CharField(max_length=50)),
                ('Applicant_city', models.CharField(max_length=50)),
                ('Applicant_state', models.CharField(max_length=50)),
                ('Applicant_country', models.CharField(max_length=50)),
                ('Applicant_pincode', models.CharField(max_length=10)),
                ('Applicant_highest_qualification', models.CharField(choices=[('post_graduate', 'Post Graduate'), ('graduate', 'Graduate'), ('higher_secondary', 'Higher Secondary'), ('high_school', 'High School')], max_length=20)),
                ('Applicant_marks_highest_qualification', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Applicant_marks_hse', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Applicant_marks_sslc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Co_applicant_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('Co_applicant_first_name', models.CharField(max_length=50)),
                ('Co_applicant_last_name', models.CharField(max_length=50)),
                ('Co_applicant_email', models.EmailField(max_length=254)),
                ('Co_applicant_phone_number', models.CharField(max_length=15)),
                ('co_applicant_relation', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('sibling', 'Sibling'), ('relative', 'Relative')], max_length=10)),
                ('co_applicant_job', models.CharField(max_length=50)),
                ('co_applicant_address', models.CharField(max_length=255)),
                ('Applicant_college_name', models.CharField(max_length=100)),
                ('Applicant_university', models.CharField(max_length=100)),
                ('Applicant_college_location', models.CharField(max_length=100)),
                ('Applicant_photo', models.ImageField(upload_to='photos/')),
                ('Applicant_aadhaar', models.FileField(upload_to='aadhaar/')),
                ('Applicant_income_certificate', models.FileField(upload_to='income_certificates/')),
                ('Applicant_pancard', models.FileField(upload_to='pancards/')),
                ('Applicant_ration_card', models.FileField(upload_to='ration_cards/')),
                ('Applicant_bank_passbook', models.FileField(upload_to='bank_passbooks/')),
                ('Applicant_any_id', models.FileField(upload_to='id_proofs/')),
                ('Applicant_birth_certificate', models.FileField(upload_to='birth_certificates/')),
                ('Applicant_sslc_certificate', models.FileField(upload_to='sslc_certificates/')),
                ('Applicant_plus2_certificate', models.FileField(upload_to='plus2_certificates/')),
                ('Applicant_highest_qualification_certificate', models.FileField(upload_to='qualification_certificates/')),
                ('Co_applicant_photo', models.ImageField(upload_to='co_photos/')),
                ('Co_applicant_aadhaar', models.FileField(upload_to='co_aadhaar/')),
                ('Co_applicant_pancard', models.FileField(upload_to='co_pancards/')),
                ('Co_applicant_bank_passbook', models.FileField(upload_to='co_bank_passbooks/')),
                ('Co_applicant_any_id', models.FileField(upload_to='co_id_proofs/')),
                ('Applicant_bonafide_certificate', models.FileField(upload_to='bonafide_certificates/')),
                ('Applicant_fee_structure', models.FileField(upload_to='fee_structures/')),
                ('Applicant_demand_letter', models.FileField(upload_to='demand_letters/')),
                ('Applicant_entrance_scorecard', models.FileField(upload_to='entrance_scorecards/')),
                ('Applicant_loan_approval', models.FileField(upload_to='loan_approvals/')),
            ],
        ),
        migrations.RemoveField(
            model_name='investorapplicationdb',
            name='investoraddress',
        ),
        migrations.RemoveField(
            model_name='investorapplicationdb',
            name='investoradhaar',
        ),
        migrations.RemoveField(
            model_name='investorapplicationdb',
            name='investorbankpass',
        ),
        migrations.RemoveField(
            model_name='investorapplicationdb',
            name='investorbankstatus',
        ),
        migrations.RemoveField(
            model_name='investorapplicationdb',
            name='investoremail',
        ),
        migrations.RemoveField(
            model_name='investorapplicationdb',
            name='investorfirstname',
        ),
        migrations.RemoveField(
            model_name='investorapplicationdb',
            name='investorlastname',
        ),
        migrations.RemoveField(
            model_name='investorapplicationdb',
            name='investorpancard',
        ),
        migrations.RemoveField(
            model_name='investorapplicationdb',
            name='investorphonenumber',
        ),
        migrations.RemoveField(
            model_name='investorapplicationdb',
            name='investorphoto',
        ),
        migrations.RemoveField(
            model_name='investorapplicationdb',
            name='nomineefirstname',
        ),
        migrations.RemoveField(
            model_name='investorapplicationdb',
            name='nomineelastname',
        ),
        migrations.RemoveField(
            model_name='investorapplicationdb',
            name='nominemphonenumber',
        ),
        migrations.AddField(
            model_name='investorapplicationdb',
            name='Investor_adhaar',
            field=models.FileField(blank=True, null=True, upload_to='documents/investor_aadhaars/'),
        ),
        migrations.AddField(
            model_name='investorapplicationdb',
            name='Investor_adress',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='investorapplicationdb',
            name='Investor_bank_pass',
            field=models.FileField(blank=True, null=True, upload_to='documents/investor_bank_passbooks/'),
        ),
        migrations.AddField(
            model_name='investorapplicationdb',
            name='Investor_bank_statement',
            field=models.FileField(blank=True, null=True, upload_to='documents/investor_bank_statements/'),
        ),
        migrations.AddField(
            model_name='investorapplicationdb',
            name='Investor_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='investorapplicationdb',
            name='Investor_first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='investorapplicationdb',
            name='Investor_last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='investorapplicationdb',
            name='Investor_pan',
            field=models.FileField(blank=True, null=True, upload_to='documents/investor_pans/'),
        ),
        migrations.AddField(
            model_name='investorapplicationdb',
            name='Investor_phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='investorapplicationdb',
            name='Investor_photo',
            field=models.FileField(blank=True, null=True, upload_to='documents/investor_photos/'),
        ),
        migrations.AddField(
            model_name='investorapplicationdb',
            name='Nominee_first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='investorapplicationdb',
            name='Nominee_last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='investorapplicationdb',
            name='Nominee_phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
