# Generated by Django 5.0.7 on 2024-08-25 08:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduInvApp', '0003_loanapplicationdb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_aadhaar',
            field=models.FileField(blank=True, null=True, upload_to='aadhaar/'),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_any_id',
            field=models.FileField(blank=True, null=True, upload_to='id_proofs/'),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_bank_passbook',
            field=models.FileField(blank=True, null=True, upload_to='bank_passbooks/'),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='birth_certificates/'),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_bonafide_certificate',
            field=models.FileField(blank=True, null=True, upload_to='bonafide_certificates/'),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_college_location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_college_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_demand_letter',
            field=models.FileField(blank=True, null=True, upload_to='demand_letters/'),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_entrance_scorecard',
            field=models.FileField(blank=True, null=True, upload_to='entrance_scorecards/'),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_father_job',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_father_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_father_phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_fee_structure',
            field=models.FileField(blank=True, null=True, upload_to='fee_structures/'),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_highest_qualification',
            field=models.CharField(choices=[('post_graduate', 'Post Graduate'), ('graduate', 'Graduate'), ('higher_secondary', 'Higher Secondary'), ('high_school', 'High School')], default='high_school', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_highest_qualification_certificate',
            field=models.FileField(blank=True, null=True, upload_to='qualification_certificates/'),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_house_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_income_certificate',
            field=models.FileField(blank=True, null=True, upload_to='income_certificates/'),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_loan_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_loan_approval',
            field=models.FileField(blank=True, null=True, upload_to='loan_approvals/'),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_marital_status',
            field=models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried'), ('nil', 'NIL')], default='nil', max_length=10),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_marks_highest_qualification',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_marks_hse',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_marks_sslc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_mother_job',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_mother_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_mother_phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_pancard',
            field=models.FileField(blank=True, null=True, upload_to='pancards/'),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_pincode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_plus2_certificate',
            field=models.FileField(blank=True, null=True, upload_to='plus2_certificates/'),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_post_office',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_ration_card',
            field=models.FileField(blank=True, null=True, upload_to='ration_cards/'),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_sslc_certificate',
            field=models.FileField(blank=True, null=True, upload_to='sslc_certificates/'),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_street_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Applicant_university',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Co_applicant_aadhaar',
            field=models.FileField(blank=True, null=True, upload_to='co_aadhaar/'),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Co_applicant_any_id',
            field=models.FileField(blank=True, null=True, upload_to='co_id_proofs/'),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Co_applicant_bank_passbook',
            field=models.FileField(blank=True, null=True, upload_to='co_bank_passbooks/'),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Co_applicant_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Co_applicant_first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Co_applicant_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Co_applicant_last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Co_applicant_pancard',
            field=models.FileField(blank=True, null=True, upload_to='co_pancards/'),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Co_applicant_phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='Co_applicant_photo',
            field=models.ImageField(blank=True, null=True, upload_to='co_photos/'),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='co_applicant_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='co_applicant_job',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanapplicationdb',
            name='co_applicant_relation',
            field=models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('sibling', 'Sibling'), ('relative', 'Relative')], default='relative', max_length=10),
        ),
    ]
