# Generated by Django 5.0.7 on 2024-08-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduInvApp', '0004_alter_loanapplicationdb_applicant_aadhaar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplicationdb',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
