# Generated by Django 5.0.7 on 2024-08-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduInvApp', '0005_loanapplicationdb_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplicationdb',
            name='Appicant_bank_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplicationdb',
            name='Applicant_account_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplicationdb',
            name='Applicant_bank_branch',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplicationdb',
            name='Applicant_ifsc_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
