# Generated by Django 5.0.7 on 2024-08-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduInvApp', '0006_loanapplicationdb_appicant_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorapplicationdb',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
