# Generated by Django 5.0.7 on 2024-09-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduInvApp', '0008_investoroffer_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvestorOffer',
        ),
    ]
