# Generated by Django 5.0.7 on 2024-09-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduInvApp', '0010_investoroffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsignupdb',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
