# Generated by Django 5.0.7 on 2024-09-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduInvApp', '0011_clientsignupdb_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplicationdb',
            name='approval_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplicationdb',
            name='token_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
