# Generated by Django 5.0.7 on 2024-09-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduInvApp', '0012_loanapplicationdb_approval_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplicationdb',
            name='approval_token',
        ),
        migrations.RemoveField(
            model_name='loanapplicationdb',
            name='token_generated_at',
        ),
        migrations.AddField(
            model_name='loanapplicationdb',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
