# Generated by Django 5.0.7 on 2024-09-11 16:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduInvApp', '0013_remove_loanapplicationdb_approval_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='investorsignupdb',
            name='investoremail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='offer',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduInvApp.loanapplicationdb'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduInvApp.investorapplicationdb'),
        ),
    ]
