# Generated by Django 5.0.7 on 2024-09-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduInvApp', '0014_offer_created_at_offer_is_accepted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='amount',
            new_name='offer_amount',
        ),
    ]
