# Generated by Django 5.0.7 on 2024-09-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduInvApp', '0015_rename_amount_offer_offer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorapplicationdb',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
