# Generated by Django 5.0.7 on 2024-10-12 13:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduInvApp', '0016_investorapplicationdb_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_repayment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_installments', models.IntegerField()),
                ('installments_paid', models.IntegerField(default=0)),
                ('next_due_date', models.DateField()),
                ('repayment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=50)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduInvApp.loanapplicationdb')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduInvApp.investorapplicationdb')),
            ],
        ),
    ]
