# Generated by Django 5.0.7 on 2024-10-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduInvApp', '0017_loanrepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorapplicationdb',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='investorapplicationdb',
            name='total_investment',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
