# Generated by Django 5.0.7 on 2024-10-20 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduInvApp', '0018_investorapplicationdb_interest_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorapplicationdb',
            name='interest_rate',
        ),
    ]
