# Generated by Django 5.0.7 on 2024-08-17 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admindb',
        ),
    ]
